
spring:
    application:
        name: dconnect-discovery
    cloud:
        loadbalancer:
            ribbon:
                enabled: false

    rabbitmq:
        password: guest
        username: guest
        host: localhost
        port: 5672


server:
    port: 8761

eureka:
    client:
        fetch-registry: false
        register-with-eureka: false